#!/usr/bin/env node

var opt = require('optimist')
        .usage('Usage: $0 SEARCH')
        .string('bbox').describe('bbox','string to replace {{bbox}} shortcuts with')
        .boolean('version').describe('version','display software version')
        .boolean('help').describe('help','print this help message'),
    argv = opt.argv,
    concat = require('concat-stream'),
    wizard = require(".");

if (argv.help) {
    return opt.showHelp();
}
if (argv.version) {
    return process.stdout.write(require('./package.json').version+'\n');
}

var search = argv._.join(" ");

if (search.length === 0) {
  // read query from stdin instead
  process.stdin.pipe(concat(generateAndPrintQuery));
} else {
  generateAndPrintQuery(search);
}


function generateAndPrintQuery(search) {
  if (typeof search !== "string") search = search.toString().trim();
  var overpassQuery = wizard.construct_query(search);
  if (overpassQuery === false) {
    return process.exit(1);
  }
  // todo: replace with something more soffisticated, see js/query.js in overpass-turbo
  if (argv.bbox) overpassQuery = overpassQuery.replace(/{{bbox}}/g, argv.bbox);
  // todo: implement more shortcut-expansions, e.g. geocoded expansion (use nominatim via request?)
  process.stdout.write(overpassQuery);
}
