#!/usr/bin/env node

var opt = require('optimist')
        .usage('Usage: $0 SEARCH')
        .boolean('version').describe('version','display software version')
        .boolean('help').describe('help','print this help message'),
    argv = opt.argv,
    concat = require('concat-stream'),
    wizard = require(".");

if (argv.help) {
    return opt.showHelp();
}
if (argv.version) {
    return process.stdout.write(require('./package.json').version+'\n');
}

var search = argv._.join(" ");

if (search.length === 0) {
  // read query from stdin
  process.stdin.pipe(concat(generateAndPrintQuery));
} else {
  generateAndPrintQuery(search);
}


function generateAndPrintQuery(search) {
  if (typeof search !== "string") search = search.toString().trim();
  // todo: implement shortcut-expansion
  process.stdout.write(wizard.construct_query(search));
}
